import test from 'node:test';import assert from 'node:assert/strict';
import {parseQuery,compileQuery,parseDashboard} from '../packages/core/semantics.ts';
import {parseSnapshot,cashPayback,day} from '../packages/core/contracts.ts';
import {readFile} from 'node:fs/promises';
const q={metrics:['cases','released_hours'],from:'2026-09-01',to:'2026-10-01',groupBy:'workflow'};
const sample=JSON.parse(await readFile(new URL('../fixtures/alpha.json',import.meta.url),'utf8'));
test('semantic compiler uses bind parameters and fixed SQL identifiers',()=>{const c=compileQuery(q,'alpha');assert.deepEqual(c.params,['alpha',q.from,q.to]);assert.ok(!c.sql.includes('alpha'));assert.ok(c.sql.includes('f.tenant_id = ?'));});
for(const mutation of [ {...q,metrics:['DROP TABLE users']},{...q,groupBy:'workflow;DELETE'},{...q,sql:'SELECT *'}, {...q,metrics:['cases','cases']},{...q,from:'2026-02-30'},{...q,to:'2026-09-01'},{...q,to:'2027-01-01'}])test(`rejects invalid query ${JSON.stringify(mutation)}`,()=>assert.throws(()=>parseQuery(mutation)));
test('dates include leap-year validation',()=>{assert.equal(day('2024-02-29'),'2024-02-29');assert.throws(()=>day('2025-02-29'));});
test('complete valid snapshot parses',()=>assert.equal(parseSnapshot(sample).records.length,12));
test('cash savings require evidence ref',()=>{const s=structuredClone(sample);s.records[0].cashSavingsVnd=100;assert.throws(()=>parseSnapshot(s));});
test('snapshot rejects duplicates',()=>{const s=structuredClone(sample);s.records[1].recordId=s.records[0].recordId;assert.throws(()=>parseSnapshot(s));});
test('snapshot rejects fractional VND and too many rows',()=>{const s=structuredClone(sample);s.records[0].runtimeCostVnd=1.2;assert.throws(()=>parseSnapshot(s));assert.throws(()=>parseSnapshot({...sample,records:[...sample.records,...sample.records]}));});
test('snapshot rejects records beyond watermark',()=>{const s=structuredClone(sample);s.records[0].day='2026-09-19';assert.throws(()=>parseSnapshot(s));});
test('negative capacity release is not clamped by SQL',()=>assert.ok(compileQuery(q,'alpha').sql.includes('baseline_minutes - f.human_minutes')));
test('cash payback distinguishes zero, negative and positive benefits',()=>{assert.equal(cashPayback(9900000,0),null);assert.equal(cashPayback(9900000,-500),null);assert.equal(cashPayback(9900000,3300000),3);});
test('dashboard definitions do not accept arbitrary SQL/JavaScript',()=>assert.throws(()=>parseDashboard({version:1,title:'A',widgets:[{id:'a',kind:'kpi',title:'A',metrics:['cases'],groupBy:'none',sql:'SELECT *'}]})));
