import test from 'node:test';
import assert from 'node:assert/strict';
import { compileCell } from '../scripts/cloudflare-config.mjs';
import { fixture, request } from '../scripts/local-adapters.mjs';
import { parseSnapshot } from '../packages/core/contracts.ts';
const inventory=()=>({schemaVersion:1,cellId:'test-01',accountId:'a'.repeat(32),workerName:'lumi-bi-test',hostname:'bi.runlumi.app',accessTeam:'test-team',accessAudience:'b'.repeat(64),control:{workerName:'lumi-bi-control',packsBucket:'lumi-bi-packs',databaseName:'control',databaseId:'11111111-1111-1111-1111-111111111111'},r2Bucket:'lumi-bi-test',tenants:[{id:'alpha',name:"Customer's tenant",binding:'TENANT_A',databaseName:'tenant-alpha',databaseId:'22222222-2222-2222-2222-222222222222',ownerSubject:'subject-opaque',sources:[{id:'operations',name:'Reviewed source'}]}]});
test('cell config separates databases, disables public development URLs, safely quotes SQL',()=>{const {config,control,controlConfig}=compileCell(inventory());assert.equal(config.workers_dev,false);assert.equal(config.preview_urls,false);assert.equal(config.d1_databases.length,1);assert.equal(controlConfig.d1_databases.length,1);assert.equal(controlConfig.d1_databases[0].binding,'CONTROL_DB');assert.equal(config.services[0].binding,'CONTROL');assert.equal(controlConfig.routes.length,0);assert.equal(config.vars.TENANT_BINDINGS,'["TENANT_A"]');assert(control[0].includes("Customer''s tenant"));});
test('cell config refuses missing account, bad database, duplicate bindings/databases, placeholder hostname',()=>{for(const mutate of [i=>i.accountId=null,i=>i.tenants[0].databaseId=i.control.databaseId,i=>i.tenants.push({...i.tenants[0]}),i=>i.hostname='bi.example.com',i=>i.accessAudience=null,i=>i.tenants[0].binding='CONTROL_DB']){const i=inventory();mutate(i);assert.throws(()=>compileCell(i));}});
test('duplicate row grain rejected even with different record IDs',()=>{const row={recordId:'r1',day:'2026-09-01',workflow:'ops',cases:1,baselineMinutes:10,humanMinutes:2,runtimeCostVnd:1,supportCostVnd:0,cashSavingsVnd:0};assert.throws(()=>parseSnapshot({sourceId:'ops',observedThrough:'2026-09-01',records:[row,{...row,recordId:'r2'}]}),/DUPLICATE_GRAIN/);});
test('stale snapshot does not publish or create R2 object',async()=>{const f=await fixture();try{const size=f.env.SOURCES.objects.size;const payload={sourceId:'ops-demo',observedThrough:'2026-09-01',records:[{recordId:'stale',day:'2026-09-01',workflow:'ops',cases:1,baselineMinutes:10,humanMinutes:2,runtimeCostVnd:1,supportCostVnd:0,cashSavingsVnd:0}]};const r=await f.api(request('/api/tenants/alpha/imports',{method:'POST',body:payload,headers:{'idempotency-key':'stale-snapshot-test'}}),f.env);assert.equal(r.status,409);assert.equal((await r.json()).error.code,'STALE_SNAPSHOT');assert.equal(f.env.SOURCES.objects.size,size);}finally{f.close();}});
test('database trigger independently prevents watermark regression',async()=>{const f=await fixture();try{const db=f.env.TENANT_A.db;db.prepare("INSERT INTO snapshots VALUES ('old','alpha','ops-demo','old-key','hash','old-key','2026-08-01','2026-09-20',1)").run();assert.throws(()=>db.prepare("UPDATE active_snapshots SET snapshot_id='old' WHERE tenant_id='alpha'").run(),/STALE_SNAPSHOT/);assert.notEqual(db.prepare("SELECT snapshot_id FROM active_snapshots WHERE tenant_id='alpha'").get().snapshot_id,'old');}finally{f.close();}});
test('editor can create config-only dashboard, duplicate ID conflicts, viewer denied',async()=>{const f=await fixture();try{const body={id:'custom-dashboard',definition:f.dashboard};const r=await f.api(request('/api/tenants/alpha/dashboards',{method:'POST',user:'alpha-editor',body}),f.env);assert.equal(r.status,201);assert.equal((await r.json()).revision,1);const again=await f.api(request('/api/tenants/alpha/dashboards',{method:'POST',body}),f.env);assert.equal(again.status,409);const viewer=await f.api(request('/api/tenants/alpha/dashboards',{method:'POST',user:'alpha-viewer',body:{...body,id:'other'}}),f.env);assert.equal(viewer.status,403);}finally{f.close();}});
test('source imports never accept an application/json-ish MIME type',async()=>{const f=await fixture();try{const r=await f.api(request('/api/tenants/alpha/query',{method:'POST',body:{},headers:{'content-type':'application/json-executable'}}),f.env);assert.equal(r.status,415);}finally{f.close();}});

test('concurrent dashboard queries remain internally consistent in the local D1 adapter',async()=>{const f=await fixture();try{const q={metrics:['cases'],groupBy:'none',from:'2026-09-01',to:'2026-10-01'};const responses=await Promise.all(Array.from({length:12},()=>f.api(request('/api/tenants/alpha/query',{method:'POST',body:q}),f.env)));for(const r of responses){assert.equal(r.status,200);assert.equal((await r.json()).data[0].cases,450);}}finally{f.close();}});
test('concurrent same-key imports converge to one published snapshot',async()=>{const f=await fixture();try{const snapshot={sourceId:'ops-demo',observedThrough:'2026-09-20',records:[{recordId:'new',day:'2026-09-20',workflow:'ops',cases:1,baselineMinutes:10,humanMinutes:2,runtimeCostVnd:1,supportCostVnd:0,cashSavingsVnd:0}]};const results=await Promise.all(Array.from({length:4},()=>f.api(request('/api/tenants/alpha/imports',{method:'POST',body:snapshot,headers:{'idempotency-key':'same-key-concurrent'}}),f.env)));const ids=[];for(const r of results){assert.equal(r.status,201);ids.push((await r.json()).snapshotId);}assert.equal(new Set(ids).size,1);assert.equal(f.env.TENANT_A.db.prepare("SELECT COUNT(*) n FROM snapshots WHERE idempotency_key='same-key-concurrent'").get().n,1);}finally{f.close();}});
test('dashboard revision uses strong ETags and rejects unquoted versions',async()=>{const f=await fixture();try{const url='/api/tenants/alpha/dashboards/operations-cost';const get=await f.api(request(url),f.env);assert.equal(get.headers.get('etag'),'"1"');const bad=await f.api(request(url,{method:'PUT',body:f.dashboard,headers:{'if-match':'1'}}),f.env);assert.equal(bad.status,428);const good=await f.api(request(url,{method:'PUT',body:f.dashboard,headers:{'if-match':'"1"'}}),f.env);assert.equal(good.status,200);assert.equal(good.headers.get('etag'),'"2"');}finally{f.close();}});

test('generated provisioning SQL creates separate control and data planes, with no default license',async()=>{
 const {LocalDatabase,LocalObjects}=await import('../scripts/local-adapters.mjs');const {createApi}=await import('../apps/api/src/api.ts');const {createControl}=await import('../apps/control/src/service.ts');const {readFile}=await import('node:fs/promises');
 const plan=compileCell(inventory()),control=new LocalDatabase(),tenant=new LocalDatabase();
 try{
  for(const file of ['0001_initial.sql','0002_control_plane.sql','0003_release_safety.sql','0004_tenant_lifecycle.sql'])control.db.exec(await readFile(new URL('../migrations/control/'+file,import.meta.url),'utf8'));
  for(const file of ['0001_initial.sql','0002_route_fence.sql'])tenant.db.exec(await readFile(new URL('../migrations/tenant/'+file,import.meta.url),'utf8'));
  control.db.exec(plan.control.join('\n'));tenant.db.exec(plan.seeds.alpha.join('\n'));
  const auth=async()=>({issuer:'https://test-team.cloudflareaccess.com',subject:'subject-opaque'});
  const controlEnv={CONTROL_DB:control,PACKS:new LocalObjects(),ACCESS_TEAM:'test-team',ACCESS_AUD:'test'};
  const service=createControl(auth),env={...plan.config.vars,CONTROL:{fetch:req=>service(req,controlEnv)},TENANT_A:tenant,SOURCES:new LocalObjects(),ASSETS:{fetch:async()=>new Response('asset')}};
  const api=createApi(auth);
  assert.equal((await api(request('/api/tenants/alpha/metrics'),env)).status,403);
  const session=await(await api(request('/api/session'),env)).json();assert.equal(session.tenants[0].name,"Customer's tenant");assert.equal(session.tenants[0].role,'owner');assert.deepEqual(session.tenants[0].features,[]);
  assert(!('CONTROL_DB' in env));assert(!('TENANT_A' in controlEnv));
 }finally{control.close();tenant.close();}
});
