import {AppError,id,integer,object,sha256,text} from './contracts.ts';
import {commerceOwner} from './commerce-normalization.ts';
import {readCommerceQueryPublication} from './commerce-publication.ts';
import type {TenantContext} from './tenant.ts';
const db=(ctx:TenantContext)=>ctx.db.withSession?ctx.db.withSession('first-primary'):ctx.db;
type Definition={metricIds:string[];from:string;toExclusive:string;dataVersion:string;blocks:{id:string;kind:'metric'|'table'|'target';metricId:string;target?:string|null}[]};
function parseDefinition(value:unknown):Definition{
 const b=object(value,['metricIds','from','toExclusive','dataVersion','blocks']);
 if(!Array.isArray(b.metricIds)||!b.metricIds.length||b.metricIds.length>10)throw new AppError(422,'INSIGHT_METRICS_INVALID');
 const metricIds=b.metricIds.map(v=>id(v));
 const from=text(b.from,32),toExclusive=text(b.toExclusive,32),dataVersion=id(b.dataVersion);
 if(from>=toExclusive)throw new AppError(422,'INSIGHT_PERIOD_INVALID');
 if(!Array.isArray(b.blocks)||b.blocks.length<1||b.blocks.length>20)throw new AppError(422,'INSIGHT_BLOCKS_INVALID');
 const ids=new Set<string>();const blocks=b.blocks.map(raw=>{const r=object(raw,['id','kind','metricId','target']),blockId=id(r.id);if(ids.has(blockId))throw new AppError(422,'INSIGHT_BLOCK_DUPLICATE');ids.add(blockId);if(r.kind!=='metric'&&r.kind!=='table'&&r.kind!=='target')throw new AppError(422,'INSIGHT_BLOCK_KIND');const kind=r.kind as Definition['blocks'][number]['kind'];const metricId=id(r.metricId);if(!metricIds.includes(metricId))throw new AppError(422,'INSIGHT_BLOCK_METRIC');const target=r.target===undefined||r.target===null?null:text(r.target,128);if(kind==='target'&&target===null)throw new AppError(422,'INSIGHT_TARGET_REQUIRED');return {id:blockId,kind,metricId,...(target===null?{}:{target})};});
 return {metricIds,from,toExclusive,dataVersion,blocks};
}
function resultFor(report:any,definition:Definition){const result:Record<string,unknown>={};for(const metricId of definition.metricIds){const value=report.metrics[metricId];if(value!==null&&typeof value!=='string')throw new AppError(503,'INSIGHT_RESULT_INVALID');result[metricId]={value,unit:metricId==='available_units'?'units':metricId==='recognized_order_count'?'count':report.currency};}return result;}
export async function createCommerceInsight(ctx:TenantContext,input:unknown){commerceOwner(ctx);const b=object(input,['id','title','definition']);const insightId=id(b.id),title=text(b.title,160),definition=parseDefinition(b.definition);const publication=await readCommerceQueryPublication(ctx,definition.dataVersion),result=resultFor(publication.report,definition),now=new Date().toISOString(),definitionJson=JSON.stringify(definition),runId='ir_'+await sha256(JSON.stringify([ctx.id,insightId,publication.id,definitionJson])).then(x=>x.slice(0,48));const database=db(ctx);const writes=await database.batch([database.prepare('INSERT INTO commerce_insights (tenant_id,id,title,revision,owner_subject,state,definition_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(tenant_id,id) DO NOTHING').bind(ctx.id,insightId,title,1,ctx.principal.subject,'SAVED',definitionJson,now,now),database.prepare('INSERT INTO commerce_insight_runs (tenant_id,insight_id,run_id,revision,publication_id,publication_hash,period_from,period_to_exclusive,query_json,result_json,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM commerce_insights WHERE tenant_id=? AND id=?) ON CONFLICT DO NOTHING').bind(ctx.id,insightId,runId,1,publication.id,publication.contentHash,definition.from,definition.toExclusive,definitionJson,JSON.stringify(result),now,ctx.id,insightId)]);if(writes.some(r=>!r.success))throw new AppError(503,'INSIGHT_PERSISTENCE_FAILED');return {id:insightId,revision:1,runId,publicationId:publication.id,publicationHash:publication.contentHash,definition,result,replayed:writes[0]?.meta.changes!==1};}
export async function readCommerceInsightsArtifacts(ctx:TenantContext,insightId?:string){commerceOwner(ctx);const rows=await db(ctx).batch([insightId?db(ctx).prepare('SELECT * FROM commerce_insights WHERE tenant_id=? AND id=?').bind(ctx.id,id(insightId)):db(ctx).prepare('SELECT * FROM commerce_insights WHERE tenant_id=? ORDER BY updated_at DESC,id DESC LIMIT 50').bind(ctx.id),db(ctx).prepare('SELECT * FROM commerce_insight_runs WHERE tenant_id=? AND (? IS NULL OR insight_id=?) ORDER BY revision DESC LIMIT 100').bind(ctx.id,insightId? id(insightId):null,insightId? id(insightId):null)]);if(rows.some(r=>!r.success))throw new AppError(503,'INSIGHT_UNAVAILABLE');const artifacts=rows[0]!.results.map((r:any)=>({...r,definition:JSON.parse(r.definition_json),runs:rows[1]!.results.filter((x:any)=>x.insight_id===r.id).map((x:any)=>({...x,query:JSON.parse(x.query_json),result:JSON.parse(x.result_json)}))}));if(insightId&&!artifacts.length)throw new AppError(404,'INSIGHT_NOT_FOUND');return {insights:artifacts};}
export async function refreshCommerceInsight(ctx:TenantContext,insightId:string,input:unknown){commerceOwner(ctx);const current=(await readCommerceInsightsArtifacts(ctx,insightId)).insights[0] as any;const expectedRevision=integer(object(input,['expectedRevision']).expectedRevision);if(current.revision!==expectedRevision)throw new AppError(409,'INSIGHT_REVISION_CONFLICT');const definition=parseDefinition(current.definition),publication=await readCommerceQueryPublication(ctx,definition.dataVersion),result=resultFor(publication.report,definition),runId='ir_'+await sha256(JSON.stringify([ctx.id,insightId,publication.id,current.revision+1])).then(x=>x.slice(0,48)),now=new Date().toISOString(),database=db(ctx);const writes=await database.batch([database.prepare('UPDATE commerce_insights SET revision=revision+1,updated_at=? WHERE tenant_id=? AND id=? AND revision=?').bind(now,ctx.id,insightId,expectedRevision),database.prepare('INSERT INTO commerce_insight_runs (tenant_id,insight_id,run_id,revision,publication_id,publication_hash,period_from,period_to_exclusive,query_json,result_json,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM commerce_insights WHERE tenant_id=? AND id=? AND revision=?) ON CONFLICT DO NOTHING').bind(ctx.id,insightId,runId,expectedRevision+1,publication.id,publication.contentHash,definition.from,definition.toExclusive,JSON.stringify(definition),JSON.stringify(result),now,ctx.id,insightId,expectedRevision+1)]);if(writes.some(r=>!r.success)||writes[0]?.meta.changes!==1)throw new AppError(409,'INSIGHT_REVISION_CONFLICT');return {id:insightId,revision:expectedRevision+1,runId,publicationId:publication.id,publicationHash:publication.contentHash,definition,result};}
export async function promoteCommerceInsight(ctx:TenantContext,insightId:string){commerceOwner(ctx);const current=(await readCommerceInsightsArtifacts(ctx,insightId)).insights[0] as any;const definition=parseDefinition(current.definition);const file=`customer/reports/${insightId}.report.tsx`;const title=String(current.title).replace(/[\\`$]/g,'');const source=`import {CommerceReportPage} from '@runlumi/ui/features/commerce-report.tsx';\n\n/** Reviewed Lumi report proposal. Query definitions stay in Git; values are resolved at runtime. */\nexport const reportDefinition=${JSON.stringify(definition,null,2)} as const;\nexport const reportTitle=${JSON.stringify(title)};\nexport function Report(){return <CommerceReportPage tenant={null as never} identity=""/>;}\n`;return {insightId,revision:current.revision,path:file,source,publicationId:definition.dataVersion,hardCodedResults:false,approvalRequired:true};}
