import {AppError,id,integer,object,sha256,text} from './contracts.ts';
import {commerceOwner} from './commerce-normalization.ts';
import {readCommerceQueryPublication} from './commerce-publication.ts';
import {parseCommerceQuery,queryCommerceReport} from './commerce-query.ts';
import type {InstallationUser} from './installation-auth.ts';
import type {Database} from './ports.ts';
const primary=(database:Database)=>database.withSession?database.withSession('first-primary'):database;
type Definition={metricIds:string[];from:string;toExclusive:string;dataVersion:string;dimension?:'source';comparison?:{from:string;toExclusive:string};blocks:{id:string;kind:'metric'|'table'|'target';metricId:string;target?:string|Record<string,string>|null}[]};
function parseDefinition(value:unknown):Definition{
 const b=object(value,['metricIds','from','toExclusive','dataVersion','dimension','comparison','blocks']);
 if(!Array.isArray(b.metricIds)||!b.metricIds.length||b.metricIds.length>10)throw new AppError(422,'INSIGHT_METRICS_INVALID');
 const metricIds=b.metricIds.map(v=>id(v));
 const from=text(b.from,32),toExclusive=text(b.toExclusive,32),dataVersion=id(b.dataVersion);
 if(from>=toExclusive)throw new AppError(422,'INSIGHT_PERIOD_INVALID');
 if(!Array.isArray(b.blocks)||b.blocks.length<1||b.blocks.length>20)throw new AppError(422,'INSIGHT_BLOCKS_INVALID');
 const ids=new Set<string>();const blocks=b.blocks.map(raw=>{const r=object(raw,['id','kind','metricId','target']),blockId=id(r.id);if(ids.has(blockId))throw new AppError(422,'INSIGHT_BLOCK_DUPLICATE');ids.add(blockId);if(r.kind!=='metric'&&r.kind!=='table'&&r.kind!=='target')throw new AppError(422,'INSIGHT_BLOCK_KIND');const kind=r.kind as Definition['blocks'][number]['kind'];const metricId=id(r.metricId);if(!metricIds.includes(metricId))throw new AppError(422,'INSIGHT_BLOCK_METRIC');let target:string|Record<string,string>|null=null;if(r.target!==undefined&&r.target!==null){if(typeof r.target==='object'&&!Array.isArray(r.target)){const t=object(r.target,['value','unit','period']),value=text(t.value,64),unit=text(t.unit,32),period=text(t.period,80);if(!/^(VND|count|units)$/.test(unit))throw new AppError(422,'INSIGHT_TARGET_UNIT');if(period!==`${from}/${toExclusive}`)throw new AppError(422,'INSIGHT_TARGET_PERIOD');target={value,unit,period};}else target=text(r.target,128);}if(kind==='target'&&target===null)throw new AppError(422,'INSIGHT_TARGET_REQUIRED');return {id:blockId,kind,metricId,...(target===null?{}:{target})};});
 let comparison:Definition['comparison'];if(b.comparison!==undefined){const c=object(b.comparison,['from','toExclusive']),compareFrom=text(c.from,32),compareTo=text(c.toExclusive,32);if(compareFrom>=compareTo)throw new AppError(422,'INSIGHT_COMPARISON_RANGE');comparison={from:compareFrom,toExclusive:compareTo};}
 if(b.dimension!==undefined&&b.dimension!=='source')throw new AppError(422,'INSIGHT_DIMENSION_UNAVAILABLE');
 return {metricIds,from,toExclusive,dataVersion,...(b.dimension===undefined?{}:{dimension:'source' as const}),...(comparison?{comparison}:{}),blocks};
}
function resultFor(report:Record<string,unknown>,definition:Definition){const query=parseCommerceQuery({contract:'lumi.query.v1',metrics:definition.metricIds.map(mid=>({id:mid,version:1})),dimensions:definition.dimension?['source']:[],filters:[{field:'business_date',op:'range',value:[definition.from,definition.toExclusive]}],...(definition.comparison?{comparison:definition.comparison}:{}),limit:50,consistency:'published',dataVersion:'cp_insight'});return queryCommerceReport(report,query);}
interface InsightRow {id:string;title:string;revision:number;owner_user_id:string;state:string;definition_json:string;created_at:string;updated_at:string}
interface RunRow {insight_id:string;run_id:string;revision:number;publication_id:string;publication_hash:string;period_from:string;period_to_exclusive:string;query_json:string;result_json:string;created_at:string}
export async function createCommerceInsight(db:Database,actor:InstallationUser,input:unknown){commerceOwner(actor);const b=object(input,['id','title','definition']);const insightId=id(b.id),title=text(b.title,160),definition=parseDefinition(b.definition);const publication=await readCommerceQueryPublication(db,definition.dataVersion),result=resultFor(publication.report as unknown as Record<string,unknown>,definition),now=new Date().toISOString(),definitionJson=JSON.stringify(definition),runId='ir_'+await sha256(JSON.stringify([insightId,publication.id,definitionJson])).then(x=>x.slice(0,48));const d=primary(db);const writes=await d.batch([d.prepare("INSERT INTO commerce_insights (id,title,revision,owner_user_id,state,definition_json,created_at,updated_at) VALUES (?,?,?,?,'SAVED',?,?,?) ON CONFLICT(id) DO NOTHING").bind(insightId,title,1,actor.id,definitionJson,now,now),d.prepare('INSERT INTO commerce_insight_runs (insight_id,run_id,revision,publication_id,publication_hash,period_from,period_to_exclusive,query_json,result_json,created_at) SELECT ?,?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM commerce_insights WHERE id=?) ON CONFLICT DO NOTHING').bind(insightId,runId,1,publication.id,publication.contentHash,definition.from,definition.toExclusive,definitionJson,JSON.stringify(result),now,insightId)]);if(writes.some(r=>!r.success))throw new AppError(503,'INSIGHT_PERSISTENCE_FAILED');return {id:insightId,revision:1,runId,publicationId:publication.id,publicationHash:publication.contentHash,definition,result,replayed:writes[0]?.meta.changes!==1};}
export async function readCommerceInsightsArtifacts(db:Database,actor:InstallationUser,insightId?:string){commerceOwner(actor);const d=primary(db),target=insightId?id(insightId):null;const rows=await d.batch([target!==null?d.prepare('SELECT * FROM commerce_insights WHERE id=?').bind(target):d.prepare('SELECT * FROM commerce_insights ORDER BY updated_at DESC,id DESC LIMIT 50'),d.prepare('SELECT * FROM commerce_insight_runs WHERE (? IS NULL OR insight_id=?) ORDER BY revision DESC LIMIT 100').bind(target,target)]);if(rows.some(r=>!r.success))throw new AppError(503,'INSIGHT_UNAVAILABLE');const artifacts=(rows[0]!.results as unknown as InsightRow[]).map(r=>({id:r.id,title:r.title,revision:r.revision,state:r.state,definition:JSON.parse(r.definition_json) as Definition,createdAt:r.created_at,updatedAt:r.updated_at,runs:(rows[1]!.results as unknown as RunRow[]).filter(x=>x.insight_id===r.id).map(x=>({runId:x.run_id,revision:x.revision,publicationId:x.publication_id,publicationHash:x.publication_hash,period:{from:x.period_from,toExclusive:x.period_to_exclusive},query:JSON.parse(x.query_json),result:JSON.parse(x.result_json),createdAt:x.created_at}))}));if(insightId&&!artifacts.length)throw new AppError(404,'INSIGHT_NOT_FOUND');return {insights:artifacts};}
export async function refreshCommerceInsight(db:Database,actor:InstallationUser,insightId:string,input:unknown){commerceOwner(actor);const current=(await readCommerceInsightsArtifacts(db,actor,insightId)).insights[0];if(!current)throw new AppError(404,'INSIGHT_NOT_FOUND');const expectedRevision=integer(object(input,['expectedRevision']).expectedRevision);if(current.revision!==expectedRevision)throw new AppError(409,'INSIGHT_REVISION_CONFLICT');const definition=parseDefinition(current.definition),publication=await readCommerceQueryPublication(db,definition.dataVersion),result=resultFor(publication.report as unknown as Record<string,unknown>,definition),runId='ir_'+await sha256(JSON.stringify([insightId,publication.id,current.revision+1])).then(x=>x.slice(0,48)),now=new Date().toISOString(),d=primary(db);const writes=await d.batch([d.prepare('UPDATE commerce_insights SET revision=revision+1,updated_at=? WHERE id=? AND revision=?').bind(now,insightId,expectedRevision),d.prepare('INSERT INTO commerce_insight_runs (insight_id,run_id,revision,publication_id,publication_hash,period_from,period_to_exclusive,query_json,result_json,created_at) SELECT ?,?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM commerce_insights WHERE id=? AND revision=?) ON CONFLICT DO NOTHING').bind(insightId,runId,expectedRevision+1,publication.id,publication.contentHash,definition.from,definition.toExclusive,JSON.stringify(definition),JSON.stringify(result),now,insightId,expectedRevision+1)]);if(writes.some(r=>!r.success)||writes[0]?.meta.changes!==1)throw new AppError(409,'INSIGHT_REVISION_CONFLICT');return {id:insightId,revision:expectedRevision+1,runId,publicationId:publication.id,publicationHash:publication.contentHash,definition,result};}
/** A reviewed TSX proposal, returned as text for owner review. Runtime model
 * output never becomes executable code: nothing here is written or imported. */
export async function promoteCommerceInsight(db:Database,actor:InstallationUser,insightId:string){commerceOwner(actor);const current=(await readCommerceInsightsArtifacts(db,actor,insightId)).insights[0];if(!current)throw new AppError(404,'INSIGHT_NOT_FOUND');const definition=parseDefinition(current.definition);const file=`customer/reports/${insightId}.report.tsx`;const title=current.title.replace(/[\\`$<>&]/g,'');const uiPackage='@runlumi/ui';const source=`import type {PageContext} from '${uiPackage}/app.tsx';\nimport {CommerceReportPage} from '${uiPackage}/features/commerce-report.tsx';\n\n/** Reviewed Lumi report proposal. Query definitions stay in Git; values are resolved at runtime. */\nexport const reportDefinition=${JSON.stringify(definition,null,2)} as const;\nexport const reportTitle=${JSON.stringify(title)};\nexport function Report(context:PageContext){return context.user?<CommerceReportPage user={context.user} identity={context.identity}/>:null;}\n`;return {insightId,revision:current.revision,path:file,source,publicationId:definition.dataVersion,hardCodedResults:false,approvalRequired:true};}
