import {AppError,sha256,type Principal,type Query, type Role} from './contracts.ts';
import {compileInstallationQuery,metrics,parseQuery,type Dashboard} from './semantics.ts';
import type {Database} from './ports.ts';
export function assertMetricScope(_role:Role,metricsRequested:readonly string[]):void{if(metricsRequested.some(metric=>!metrics.some(item=>item.id===metric)))throw new AppError(400,'UNKNOWN_METRIC')}
export function assertDashboardScope(_role:Role,definition:Dashboard):void{for(const widget of definition.widgets)assertMetricScope(_role,widget.metrics)}
export async function executeInstallationQueries(db:Database,principal:Principal,role:Role,queries:Query[]){
 const plans=queries.map(compileInstallationQuery),primary=db.withSession?db.withSession('first-primary'):db;
 const rows=await primary.batch([primary.prepare("SELECT s.id AS source_id,p.id,p.content_hash,p.observed_through,p.ingested_at FROM sources s LEFT JOIN active_snapshots a ON a.source_id=s.id LEFT JOIN snapshots p ON p.id=a.snapshot_id WHERE s.state='active' ORDER BY s.id LIMIT 21"),...plans.map(plan=>primary.prepare(plan.sql).bind(...plan.params))]);
 if(rows.length!==queries.length+1||rows.some(row=>!row.success))throw new AppError(503,'QUERY_UNAVAILABLE');
 const sources=rows[0]!.results;if(sources.length>20||rows.slice(1).some(row=>row.results.length>200))throw new AppError(422,'RESULT_BUDGET_EXCEEDED');const provenance=sources.filter(source=>source.id!==null),missingSources=sources.filter(source=>source.id===null).map(source=>source.source_id);const scopeDigest=await sha256(JSON.stringify([principal.issuer,principal.subject,role]));const context={scopeDigest,definitionVersion:'operations-v1',reportingTimezone:'Asia/Ho_Chi_Minh',currency:'VND',snapshotVector:provenance.map(source=>({sourceId:source.source_id,snapshotId:source.id,contentHash:source.content_hash})),windows:queries.map(query=>[query.from,query.to])};const contextHash=await sha256(JSON.stringify(context));const generatedAt=new Date().toISOString();
 const results=queries.map((query,index)=>{const requiredThrough=new Date(Date.parse(query.to)-86400000).toISOString().slice(0,10);const behind=provenance.filter(source=>String(source.observed_through)<requiredThrough).map(source=>source.source_id);const qualityState=provenance.length===0?'NO_PUBLISHED_DATA':missingSources.length?'MISSING_SOURCE':behind.length?'BEHIND_REQUESTED_PERIOD':'COVERAGE_UNVERIFIED';return {data:rows[index+1]!.results,meta:{...context,contextHash,from:query.from,toExclusive:query.to,provenance,sourceCount:provenance.length,expectedSourceCount:sources.length,missingSources,noPublishedData:provenance.length===0,qualityState,behindRequestedPeriod:behind,generatedAt,sourceCompletenessCertified:false,rowsRead:rows[index+1]!.meta.rows_read??null,caveat:'Released hours are capacity, not cash savings.'}}});
 if(new TextEncoder().encode(JSON.stringify(results)).byteLength>512000)throw new AppError(422,'RESULT_BUDGET_EXCEEDED');return {context,contextHash,results};
}
