import {useState,type FormEvent} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {api,type Tenant} from '../lib/api.ts';
import {commercePermitted,exactNumber,localInstant,commerceLabels,downloadCommerce,type CommercePublication,type CommerceReport,type CommerceDecision} from '../lib/commerce.ts';
import {commerceFindings} from '@runlumi/core/commerce-insights.ts';
import {Card,CardHeader,CardTitle,CardContent} from '../components/ui/card.tsx';
import {Button} from '../components/ui/button.tsx';
import {Loading,ErrorState,Empty} from '../components/states.tsx';

export function ReportMetrics({report}:{report:CommerceReport}){
 const cards=[['Doanh số hàng đã ghi nhận','net_merchandise_sales','Hàng ghi nhận không gồm thuế bán hàng tách được; đã trừ giảm giá và hàng hoàn.'],['Giá vốn lịch sử','cogs','Giá vốn của phần hàng đã ghi nhận, không lấy giá hiện tại.'],['Đóng góp trước quảng cáo','contribution_pre_ads','Lãi gộp cộng thu vận chuyển, hỗ trợ được hưởng, trừ phí biến đổi. Thiếu thành phần thì không tính.']] as const;
 return <div className="commerce-metrics">{cards.map(([label,key,definition])=><Card key={key}><CardContent><h2>{label}</h2><div className="commerce-number" data-metric={key}>{exactNumber(report.metrics[key])}</div><small>{report.metrics[key]===null?'Không thay giá trị chưa biết bằng 0.':'VND'}</small><p className="metric-definition">{definition}</p></CardContent></Card>)}</div>;
}
export function ReportEvidence({report,publicationId,hash}:{report:CommerceReport;publicationId?:string;hash?:string}){
 return <Card className="mt-6"><CardHeader><CardTitle>Nguồn, định nghĩa và giới hạn</CardTitle></CardHeader><CardContent>
  <div className="evidence-tags">{report.warnings.map(w=><span className="tag" key={w}>{commerceLabels[w]??w}</span>)}</div>
  <dl className="mt-6"><dt>Phạm vi nguồn</dt><dd>{localInstant(report.window.from)} đến trước {localInstant(report.window.toExclusive)} (giờ Việt Nam)</dd><dt>Cách ghi nhận</dt><dd>Nhóm đơn theo ngày đặt, cập nhật đến mốc quan sát của từng nguồn. Không phải báo cáo lãi lỗ theo ngày hạch toán.</dd><dt>Cơ sở thuế</dt><dd>Hàng không gồm thuế bán hàng tách được; chi phí không gồm thuế đầu vào có thể thu hồi. Tiền và đối soát giữ giá trị chuyển thực tế.</dd><dt>Phiên bản định nghĩa</dt><dd><code>{report.semanticVersion}</code></dd>{publicationId&&<><dt>Bản công bố</dt><dd><code>{publicationId}</code></dd><dt>Dấu kiểm toàn vẹn</dt><dd><code>{hash}</code></dd></>}</dl>
  <div className="table-scroll mt-6" role="region" aria-label="Bằng chứng nguồn" tabIndex={0}><table><caption className="sr-only">Nguồn được chốt trong cùng bản công bố</caption><thead><tr><th>Nguồn / phạm vi</th><th>Mốc quan sát</th><th>Số quan sát</th><th>Truy vết</th></tr></thead><tbody>{report.sources.map(s=><tr key={s.normalizationId}><td>{s.provider} / {s.sourceAccountId}<small>{s.resourceType}</small></td><td>{localInstant(s.observedAt)}</td><td className="numeric">{s.recordCount}</td><td><details><summary>Mã nguồn và hash</summary><code>{s.normalizationId}<br/>{s.rawContentHash}</code></details></td></tr>)}</tbody></table></div>
  <p className="muted">{report.checks.length} số kiểm soát được khai báo riêng. Khớp số khai báo không tự chứng minh nguồn đầy đủ hoặc chứng từ độc lập.</p>
  {report.exclusions.length>0&&<details className="mt-6"><summary>{report.exclusions.length} quan sát bị loại khi hợp nhất nguồn</summary><pre className="json-inspector">{JSON.stringify(report.exclusions,null,2)}</pre></details>}
 </CardContent></Card>;
}
function MoneyTables({report}:{report:CommerceReport}){
 const metrics=[['Đơn đã ghi nhận','recognized_order_count','đơn'],['Lợi nhuận gộp trong phạm vi','gross_profit','VND'],['Bình quân doanh số / đơn ghi nhận','net_aov','VND'],['Đối soát cuối cùng phải nhận','expected_settlement','VND'],['Tiền nhận theo chứng từ được gắn','observed_cash_received','VND'],['Chênh lệch đối soát còn mở','unreconciled_payout_amount','VND']] as const;
 return <><ReportMetrics report={report}/><Card className="mt-6"><CardHeader><CardTitle>Tách bán hàng, đối soát và tiền</CardTitle></CardHeader><CardContent><dl>{metrics.map(([label,key,unit])=><div className="metric-line" key={key}><dt>{label}</dt><dd data-metric={key}>{exactNumber(report.metrics[key])} {report.metrics[key]!==null&&<small>{unit}</small>}</dd></div>)}</dl><p className="muted">Chênh lệch không phải khoản lỗ đã xác nhận hoặc tiền đã thu hồi. Không tự gắn tiền ngân hàng cho đơn theo số tiền giống nhau.</p></CardContent></Card>
 <Card className="mt-6"><CardHeader><CardTitle>Đơn trong bản công bố</CardTitle></CardHeader><CardContent><div className="table-scroll" role="region" aria-label="Đơn hàng" tabIndex={0}><table><thead><tr><th>Mã nguồn</th><th>Ngày đặt (VN)</th><th>Ghi nhận</th><th>Giá vốn</th><th>Phí biến đổi</th></tr></thead><tbody>{report.orders.slice(0,50).map(o=><tr key={o.canonicalId}><td><code>{o.id}</code></td><td>{localInstant(o.orderedAt)}</td><td>{o.recognizedAt?localInstant(o.recognizedAt):'Chưa ghi nhận'}</td><td className="numeric">{exactNumber(o.cogs)}</td><td className="numeric">{exactNumber(o.variableFees)}</td></tr>)}</tbody></table></div><small>Hiển thị {Math.min(report.orders.length,50)} / {report.orders.length} đơn; bản JSON giữ đầy đủ phạm vi.</small></CardContent></Card></>;
}
function StockTable({report}:{report:CommerceReport}){
 return <Card><CardHeader><p className="eyebrow">QUAN SÁT KHO VẬT LÝ</p><CardTitle>Hàng nào thực sự khả dụng?</CardTitle></CardHeader><CardContent><p className="quality-note">Không cộng tồn theo thời gian hoặc tồn phân bổ trên các kênh. Chưa có dự báo nhu cầu, số ngày đủ hàng hay đề nghị mua tự động.</p><div className="table-scroll" role="region" aria-label="Tồn kho vật lý" tabIndex={0}><table><thead><tr><th>Kho / SKU</th><th>Quan sát lúc</th><th>Trong kho</th><th>Giữ hàng</th><th>Khả dụng nguồn cấp</th></tr></thead><tbody>{report.inventory.slice(0,100).map(s=><tr key={s.canonicalId}><td>{s.poolId}<small>{s.variantId}</small></td><td>{localInstant(s.observedAt)}</td><td className="numeric">{exactNumber(s.onHand)}</td><td className="numeric">{exactNumber(s.reserved)}</td><td className="numeric">{exactNumber(s.available)}</td></tr>)}</tbody></table></div><small>{report.inventory.length?`Hiển thị ${Math.min(report.inventory.length,100)} / ${report.inventory.length} cặp kho và SKU. Số khả dụng nguồn cấp không bị trừ giữ hàng lần nữa.`:'Chưa có quan sát tồn kho trong bản này.'}</small></CardContent></Card>;
}
function Decisions({tenant,identity,report,publicationId}:{tenant:Tenant;identity:string;report:CommerceReport;publicationId:string}){
 const base=`/api/tenants/${tenant.id}`,client=useQueryClient(),findings=commerceFindings(report);
 const q=useQuery({queryKey:['commerce-decisions',identity,tenant.id,publicationId],queryFn:({signal})=>api<{decisions:CommerceDecision[]}>(base+'/commerce-decisions',identity,{signal})});
 const [rationale,setRationale]=useState(''),[findingId,setFindingId]=useState(''),[dueOn,setDueOn]=useState('');
 const mutation=useMutation({mutationFn:async(action:{kind:'create'}|{kind:'move';decision:CommerceDecision;state:string;note:string})=>action.kind==='create'?api(base+'/commerce-decisions',identity,{method:'POST',body:{publicationId,findingId,rationale,dueOn:dueOn||null}}):api(base+'/commerce-decisions/'+action.decision.id,identity,{method:'PUT',revision:action.decision.revision,body:{state:action.state,note:action.note,outcomePublicationId:action.state==='RESOLVED'?publicationId:null}}),onSuccess:()=>{setFindingId('');setRationale('');void client.invalidateQueries({queryKey:['commerce-decisions',identity,tenant.id]});}});
 const submit=(e:FormEvent)=>{e.preventDefault();mutation.mutate({kind:'create'});};
 return <div className="stack"><Card><CardHeader><CardTitle>Điều gì cần kiểm tra?</CardTitle></CardHeader><CardContent><p className="quality-note">Các điều kiện quan sát được, không phải kết luận nguyên nhân. Ghi nhận việc không cấp quyền gửi lệnh, sửa hệ thống hoặc chuyển tiền.</p>
 <div className="finding-list">{findings.map(f=><article key={f.id}><div><h3>{f.title}</h3><p>{f.explanation}</p><small>{f.entityId}</small><p className="muted">{f.nextStep}</p></div><div><strong>{f.value===null?'Thiếu dữ liệu':exactNumber(f.value)}</strong><Button className="mt-3" variant="outline" onClick={()=>{setFindingId(f.id);mutation.reset();}}>Ghi nhận việc</Button></div></article>)}{!findings.length&&<Empty>Không thấy điều kiện cảnh báo trong phạm vi này. Điều đó không chứng minh toàn bộ doanh nghiệp không có vấn đề.</Empty>}</div>
 {findingId&&<form className="commerce-form mt-6" onSubmit={submit}><h3>{findings.find(f=>f.id===findingId)?.title}</h3><label>Lý do và việc sẽ kiểm tra<textarea autoFocus required maxLength={1000} value={rationale} onChange={e=>setRationale(e.target.value)}/></label><label>Hạn kiểm tra (không bắt buộc)<input type="date" value={dueOn} onChange={e=>setDueOn(e.target.value)}/></label><div className="form-actions"><Button type="submit" disabled={mutation.isPending}>Lưu việc cần kiểm tra</Button><Button variant="ghost" onClick={()=>setFindingId('')}>Hủy</Button></div></form>}
 </CardContent></Card>{mutation.isError&&<ErrorState error={mutation.error}/>}
 <Card><CardHeader><CardTitle>Sổ quyết định và kết quả</CardTitle></CardHeader><CardContent>{q.isPending?<Loading/>:q.isError?<ErrorState error={q.error}/>:q.data.decisions.length?<div className="decision-list">{q.data.decisions.map(d=><DecisionRow key={`${d.id}:${d.revision}`} decision={d} busy={mutation.isPending} onMove={(state,note)=>mutation.mutate({kind:'move',decision:d,state,note})}/>)}</div>:<Empty>Chưa có việc cần kiểm tra được ghi nhận.</Empty>}<p className="muted">Chỉ xác nhận kết quả khi một bản nguồn mới, cùng phạm vi, vẫn chứa đối tượng và cho thấy điều kiện đã hết. “Đã giải quyết” không tự tạo khoản tiền thu hồi.</p></CardContent></Card></div>;
}
function DecisionRow({decision:d,busy,onMove}:{decision:CommerceDecision;busy:boolean;onMove:(state:string,note:string)=>void}){
 const choices:Record<string,string[]>={OPEN:['INVESTIGATING','ACCEPTED_LIMITATION'],INVESTIGATING:['AWAITING_OUTCOME','ACCEPTED_LIMITATION'],AWAITING_OUTCOME:['INVESTIGATING','RESOLVED','ACCEPTED_LIMITATION']};
 const options=choices[d.state]??[],[note,setNote]=useState(''),[state,setState]=useState(options[0]??'');
 return <article><div className="result-actions"><h3>{d.finding.title}</h3><span className="tag">{commerceLabels[d.state]}</span></div><p>{d.rationale}</p><small>Người phụ trách: {d.owner_subject}{d.due_on?` · Hạn ${d.due_on}`:''}</small>{d.outcome_note&&<p className="muted">Ghi nhận gần nhất: {d.outcome_note}</p>}{options.length>0&&<form className="commerce-form compact mt-4" onSubmit={e=>{e.preventDefault();onMove(state,note);}}><label>Cập nhật trạng thái<select value={state} onChange={e=>setState(e.target.value)}>{options.map(o=><option key={o} value={o}>{commerceLabels[o]}</option>)}</select></label><label>Bằng chứng hoặc ghi chú<textarea required maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><Button type="submit" disabled={busy}>Lưu cập nhật</Button></form>}</article>;
}
export function CommerceReportPage(props:{tenant:Tenant;identity:string}){
 if(!commercePermitted(props.tenant))return <Empty>Chỉ chủ doanh nghiệp được cấp quyền nhập dữ liệu mới xem được bản thương mại này.</Empty>;
 return <AuthorizedReportPage {...props}/>;
}
function AuthorizedReportPage({tenant,identity}:{tenant:Tenant;identity:string}){
 const [tab,setTab]=useState('money'),base=`/api/tenants/${tenant.id}`;
 const q=useQuery({queryKey:['commerce-report',identity,tenant.id],queryFn:({signal})=>api<CommercePublication>(base+'/commerce-publications',identity,{signal})});
 const download=useMutation({mutationFn:async(format:'csv'|'json')=>{const id=q.data?.publication?.id;if(id)await downloadCommerce(`${base}/commerce-exports/${id}?format=${format}`,identity,`lumi-${id}.${format}`);}});
 if(q.isPending)return <Loading/>;if(q.isError)return <ErrorState error={q.error} retry={()=>q.refetch()}/>;
 const publication=q.data.publication;
 return <><div className="page-title"><div><p className="eyebrow">BẢN CÔNG BỐ CÓ THỂ KIỂM TRA</p><h1>Số rõ, rồi mới quyết.</h1><p>Mỗi số đi cùng phạm vi, nguồn và giới hạn. Không dùng trạng thái “đã nhập” thay cho “đã đúng”.</p></div><Link className="inline-link" to="/commerce-data">Quản lý nguồn và bản nhập →</Link></div>
 {!publication?<Empty>Chưa có bản thương mại được công bố. Nhập nguồn, kiểm tra và duyệt bản xem trước để bắt đầu.</Empty>:<>
 <div className="report-context"><span className="tag">Số tạm tính · Chưa chứng nhận đầy đủ nguồn</span><small>Công bố {localInstant(publication.publishedAt)}</small><code>{publication.id}</code></div>
 {!!q.data.health?.pendingOrQuarantined.length&&<p className="quality-note">Có bản nhập mới chưa công bố hoặc nguồn cần kiểm tra. Bên dưới vẫn là bản công bố được ghi rõ, không tự trộn số mới.</p>}
 <div className="result-actions"><div className="report-tabs" role="group" aria-label="Nội dung thương mại">{[['money','Tiền & lợi nhuận'],['stock','Kho vật lý'],['decisions','Việc & kết quả']].map(([key,label])=><Button key={key} variant={tab===key?'default':'outline'} aria-pressed={tab===key} onClick={()=>setTab(key!)}>{label}</Button>)}</div><div className="form-actions"><Button variant="outline" disabled={download.isPending} onClick={()=>download.mutate('csv')}>Xuất số CSV</Button><Button variant="ghost" disabled={download.isPending} onClick={()=>download.mutate('json')}>Bản JSON</Button></div></div>
 {download.isError&&<ErrorState error={download.error}/>}<div key={publication.id}>{tab==='money'?<MoneyTables report={publication.report}/>:tab==='stock'?<StockTable report={publication.report}/>:<Decisions tenant={tenant} identity={identity} report={publication.report} publicationId={publication.id}/>}</div><ReportEvidence report={publication.report} publicationId={publication.id} hash={publication.contentHash}/>
 </>}
 </>;
}
