import {useQuery} from '@tanstack/react-query';import {api,type Configuration,type Tenant} from '../lib/api.ts';
import {Card,CardHeader,CardTitle,CardContent} from '../components/ui/card.tsx';import {Loading,ErrorState,Empty} from '../components/states.tsx';
export function ConfigurationPage({tenant,identity}:{tenant:Tenant;identity:string}){
 const q=useQuery({queryKey:['configuration',identity,tenant.id],queryFn:({signal})=>api<Configuration>(`/api/tenants/${tenant.id}/configuration`,identity,{signal})});
 if(q.isPending)return <Loading/>;if(q.isError)return <ErrorState error={q.error}/>;
 const active=q.data.active;
 return <><div className="page-title"><div><p className="eyebrow">TENANT PACKS</p><h1>Cấu hình riêng. Một nền tảng chung.</h1><p>Dashboard, truy vấn và AI profile có phiên bản, được review trước khi công bố.</p></div></div>
 {!active?<Empty>Tenant đang dùng pack mặc định. Chưa kích hoạt bản cấu hình từ Git.</Empty>:<div className="config-grid"><Card><CardHeader><p className="eyebrow">BẢN ĐANG HIỆU LỰC</p><CardTitle>{active.name}</CardTitle></CardHeader><CardContent><dl><dt>Release</dt><dd><code>{active.releaseId}</code></dd><dt>Commit do operator khai báo</dt><dd><code>{active.sourceCommit.slice(0,12)}</code></dd><dt>Nguồn gốc Git</dt><dd>Chưa xác minh attestation</dd><dt>Revision</dt><dd>{active.revision}</dd><dt>Truy vấn được duyệt</dt><dd>{active.queries.map(q=>q.id).join(', ')||'Chưa khai báo'}</dd></dl></CardContent></Card><Card><CardHeader><p className="eyebrow">AI PROFILE</p><CardTitle>Mô hình theo từng doanh nghiệp</CardTitle></CardHeader><CardContent><dl><dt>Provider instance</dt><dd>{active.ai.providerInstanceRef}</dd><dt>Model alias</dt><dd>{active.ai.modelRef}</dd><dt>Ngân sách khai báo</dt><dd>${active.ai.dailyBudgetUsd}/ngày</dd></dl><p className="notice-small">Mới hỗ trợ lưu và kiểm tra cấu hình. Suy luận AI và bộ đếm ngân sách chưa được bật.</p></CardContent></Card></div>}
 <Card className="mt-6"><CardHeader><CardTitle>Quy trình công bố</CardTitle></CardHeader><CardContent><div className="release-flow"><span>Git source</span><span>Kiểm tra</span><span>Review</span><span>Release bất biến</span><span>Kích hoạt riêng tenant</span></div><p className="muted">Bản hiện tại đăng ký bundle qua operator; chưa tự xác minh PR/GitHub attestation. API key không nằm trong Git. Quay lại release trước chỉ phục hồi cấu hình, không đảo ngược dữ liệu.</p></CardContent></Card></>;
}
