import {createServer} from 'node:http';
import {readFile,access} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve,sep} from 'node:path';
import {createApi} from '@runlumi/core/api.ts';
import {LocalDatabase,LocalObjects} from '@runlumi/cloudflare/testing.ts';
const root=fileURLToPath(new URL('../',import.meta.url)),webRoot=fileURLToPath(new URL('../apps/web/dist/',import.meta.url));try{await access(new URL('../apps/web/dist/index.html',import.meta.url))}catch{throw new Error('Frontend bundle missing. Run npm run build:web first.')}
// Default: demo mode with synthetic data and switchable local identities.
// `npm run dev -- --strict`: an empty installation exercising the real
// first-run setup, direct sign-in and role journey. Demo headers never reach a
// non-demo server, and neither mode needs a Lumi-operated service.
const strict=process.argv.includes('--strict')||process.env.LUMI_STRICT==='1';
const demo=!strict;
const portArg=process.argv.indexOf('--port');
const port=portArg>=0?Number(process.argv[portArg+1]):8787;
const db=new LocalDatabase(),objects=new LocalObjects();
// Both modes run the real installation schema; demo additionally seeds synthetic data.
const {readdir}=await import('node:fs/promises');
for(const file of (await readdir(new URL('../migrations/installation/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())db.db.exec(await readFile(new URL(`../migrations/installation/${file}`,import.meta.url),'utf8'));
if(demo){const now=new Date().toISOString();db.db.exec(`INSERT INTO installation VALUES(1,'Local installation', '${now}', '0.1.0'); INSERT INTO users VALUES('local-owner','local','local-owner','Local owner','owner','active','${now}','${now}'); INSERT INTO users VALUES('local-viewer','local','local-viewer','Local viewer','viewer','active','${now}','${now}'); INSERT INTO sources VALUES('ops-demo','Synthetic operations','active'); INSERT INTO snapshots VALUES('demo-snapshot','ops-demo','demo-key-1','demo-hash','demo-object.json','2026-09-30','${now}',3); INSERT INTO active_snapshots VALUES('ops-demo','demo-snapshot'); INSERT INTO workflow_facts VALUES ('demo-snapshot','f1','2026-09-15','support',200,120,30,1000,500,0,NULL),('demo-snapshot','f2','2026-09-15','fulfillment',150,90,45,800,200,0,NULL),('demo-snapshot','f3','2026-09-15','invoicing',100,240,120,1200,300,0,NULL); INSERT INTO dashboards VALUES('demo-overview','${JSON.stringify({version:1,title:'Tổng quan vận hành',widgets:[{id:'cases-kpi',kind:'kpi',title:'Lượt xử lý',metrics:['cases'],groupBy:'none'},{id:'hours-bar',kind:'bar',title:'Giờ công được giải phóng',metrics:['released_hours'],groupBy:'workflow'},{id:'cost-table',kind:'table',title:'Chi phí theo quy trình',metrics:['runtime_cost_vnd','net_cash_benefit_vnd'],groupBy:'workflow'}]}).replaceAll("'","''")}',1,'${now}');`);}
const env={DB:db,SOURCES:objects,ASSETS:{async fetch(){return new Response('asset')}}};
const api=createApi(async request=>({issuer:'local',subject:request.headers.get('x-demo-user')??'local-owner'}),demo,{standalone:true});
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.woff2':'font/woff2','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'};const server=createServer(async(req,res)=>{try{if(![`localhost:${port}`,`127.0.0.1:${port}`].includes(req.headers.host??'')){res.writeHead(403);res.end('Loopback host required');return}const url=new URL(req.url??'/',`http://${req.headers.host}`);if(url.pathname.startsWith('/api/')||url.pathname==='/healthz'){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>131072){res.writeHead(413);res.end();return}chunks.push(chunk)}const headers=new Headers();for(const[k,v]of Object.entries(req.headers))if(typeof v==='string')headers.set(k,v);if(demo&&!headers.has('x-demo-user'))headers.set('x-demo-user','local-owner');const method=req.method??'GET';const request=new Request(url,{method,headers,...(!['GET','HEAD'].includes(method)?{body:Buffer.concat(chunks)}:{})});const response=await api(request,env);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));return}const target=resolve(webRoot,`.${decodeURIComponent(!url.pathname.split('/').at(-1).includes('.')?'/index.html':url.pathname)}`);if(!target.startsWith(webRoot.endsWith(sep)?webRoot:webRoot+sep)){res.writeHead(403);res.end();return}const type=Object.entries(mime).find(([ext])=>target.endsWith(ext))?.[1];if(!type){res.writeHead(404);res.end();return}res.writeHead(200,{'Content-Type':type,'X-Content-Type-Options':'nosniff','Cache-Control':'no-store'});res.end(await readFile(target))}catch(error){res.writeHead(500);res.end('Local development error');console.error(error)}});
const banner=strict?'STRICT: empty installation. Open the app to run first-run setup and create the administrator.':'DEMO: synthetic data only. Run `npm run dev -- --strict` for the real setup and sign-in journey.';
server.listen(port,'127.0.0.1',()=>console.log(`Lumi BI: http://127.0.0.1:${port}\n${banner}\nLoopback-only.`));process.on('SIGINT',()=>server.close(()=>{db.close();process.exit(0)}));
