import {createServer} from 'node:http';
import {readFile,access} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve,sep} from 'node:path';
import {createApi} from '@runlumi/core/api.ts';
import {LocalDatabase,LocalObjects} from '@runlumi/cloudflare/testing.ts';
const root=fileURLToPath(new URL('../',import.meta.url)),webRoot=fileURLToPath(new URL('../apps/web/dist/',import.meta.url));try{await access(new URL('../apps/web/dist/index.html',import.meta.url))}catch{throw new Error('Frontend bundle missing. Run npm run build:web first.')}
const db=new LocalDatabase(),objects=new LocalObjects();db.db.exec(await readFile(new URL('../migrations/installation/0001_initial.sql',import.meta.url),'utf8'));const now=new Date().toISOString();db.db.exec(`INSERT INTO installation VALUES(1,'Local installation', '${now}', '0.1.0'); INSERT INTO users VALUES('local-owner','local','local-owner','Local owner','owner','active','${now}','${now}'); INSERT INTO users VALUES('local-viewer','local','local-viewer','Local viewer','viewer','active','${now}','${now}'); INSERT INTO sources VALUES('ops-demo','Synthetic operations','active');`);
const env={DB:db,SOURCES:objects,ASSETS:{async fetch(){return new Response('asset')}}};const api=createApi(async request=>({issuer:'local',subject:request.headers.get('x-demo-user')??'local-owner'}),true,{standalone:true});
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.woff2':'font/woff2','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'};const server=createServer(async(req,res)=>{try{if(!['localhost:8787','127.0.0.1:8787'].includes(req.headers.host??'')){res.writeHead(403);res.end('Loopback host required');return}const url=new URL(req.url??'/',`http://${req.headers.host}`);if(url.pathname.startsWith('/api/')||url.pathname==='/healthz'){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>65536){res.writeHead(413);res.end();return}chunks.push(chunk)}const headers=new Headers();for(const[k,v]of Object.entries(req.headers))if(typeof v==='string')headers.set(k,v);if(!headers.has('x-demo-user'))headers.set('x-demo-user','local-owner');const method=req.method??'GET';const request=new Request(url,{method,headers,...(!['GET','HEAD'].includes(method)?{body:Buffer.concat(chunks)}:{})});const response=await api(request,env);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));return}const target=resolve(webRoot,`.${decodeURIComponent(!url.pathname.split('/').at(-1).includes('.')?'/index.html':url.pathname)}`);if(!target.startsWith(webRoot.endsWith(sep)?webRoot:webRoot+sep)){res.writeHead(403);res.end();return}const type=Object.entries(mime).find(([ext])=>target.endsWith(ext))?.[1];if(!type){res.writeHead(404);res.end();return}res.writeHead(200,{'Content-Type':type,'X-Content-Type-Options':'nosniff','Cache-Control':'no-store'});res.end(await readFile(target))}catch(error){res.writeHead(500);res.end('Local development error');console.error(error)}});server.listen(8787,'127.0.0.1',()=>console.log('Lumi BI: http://127.0.0.1:8787\nSynthetic data only. Loopback-only.'));process.on('SIGINT',()=>server.close(()=>{db.close();process.exit(0)}));
