import {useQuery} from '@tanstack/react-query';import {api,type Overview} from '@/lib/api';
import {Loading,ErrorState} from '@/components/states';import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card';
export function ControlPage({identity}:{identity:string}){
 const q=useQuery({queryKey:['control',identity],queryFn:({signal})=>api<Overview>('/api/control/overview',identity,{signal})});
 if(q.isPending)return <Loading/>;if(q.isError)return <ErrorState error={q.error}/>;
 return <><div className="page-title"><div><p className="eyebrow">PLATFORM OPERATIONS</p><h1>Control Plane</h1><p>Quản lý tổ chức, danh tính và quyền sử dụng. Không đọc dữ liệu BI của khách.</p></div><span className="tag">Metadata only</span></div>
 <div className="summary-grid"><Card><CardContent><p className="eyebrow">TENANTS HIỂN THỊ</p><p className="kpi-value">{q.data.tenants.length}</p></CardContent></Card><Card><CardContent><p className="eyebrow">USERS HIỂN THỊ</p><p className="kpi-value">{q.data.users.length}</p></CardContent></Card><Card><CardContent><p className="eyebrow">GIT RELEASES ĐANG DÙNG</p><p className="kpi-value">{q.data.tenants.filter(t=>t.active_release_id).length}</p></CardContent></Card></div>
 <Card><CardHeader><CardTitle>Doanh nghiệp và licensing</CardTitle></CardHeader><CardContent><div className="table-scroll"><table><thead><tr><th>Doanh nghiệp</th><th>Cell</th><th>Gói</th><th>Trạng thái license</th><th>Config</th></tr></thead><tbody>{q.data.tenants.map(t=><tr key={t.id}><td><strong>{t.name}</strong><small>{t.id}</small></td><td>{t.cell_id}</td><td>{t.plan_id??'Chưa cấp'}</td><td><span className="tag">{t.license_state??'missing'}</span></td><td>{t.active_release_id?`Git · rev ${t.config_revision}`:'Mặc định'}</td></tr>)}</tbody></table></div></CardContent></Card>
 <Card className="mt-6"><CardHeader><CardTitle>Danh tính trong hệ thống</CardTitle></CardHeader><CardContent><div className="table-scroll"><table><thead><tr><th>Subject</th><th>Trạng thái</th><th>Membership đang hiệu lực</th></tr></thead><tbody>{q.data.users.map(u=><tr key={`${u.issuer}:${u.subject}`}><td>{u.subject}</td><td>{u.state}</td><td>{u.tenant_count}</td></tr>)}</tbody></table></div><p className="muted">Tối đa {q.data.limit} mục mỗi danh sách trong bản hiện tại. Platform operator không tự có quyền xem dữ liệu của một tenant.</p></CardContent></Card></>;
}
